.MODEL SMALL

.STACK 100H

.DATA
hexdigit db 'ENTER A HEX DIGIT $'
decimal db 'IN DECIMAL IT IS $'
       
.CODE
MAIN PROC

;initizlize DS

MOV AX,@DATA
MOV DS,AX

; SHOW THE PROMPT OF TAKING INPUT
MOV AH,9
LEA DX,hexdigit
INT 21H

;TAKING INPUT FROM USER
MOV AH,1
INT 21H
MOV BL,AL;INPUT NIYE BL REGISTER E SAVE KORLAM
SUB BL,17D ;LET A,B,C ... 0,1,2 . FOR ACHIEVING IT WE NEED TO SUBTRACT A,B,C ASCII VALUE TO 17 DECIMAL TO GET REQUIRED RESULT. 

;GIVING NEW LINE
MOV AH,2
MOV DL,10 
INT 21H
MOV DL,13
INT 21H 

;OUTPUT MESSAGE SHOW
MOV AH,9
LEA DX,decimal
INT 21H


;EKON SOBGULA OUTPUT ER AGE 1 ANAR JONNE SOBAR AGE 1 PRINT KORE NIBO 49D = '1' DIYE
MOV DL,49D
;PRINT FUNCTION
MOV AH,2
INT 21H  


;EKON UPORER HEX DIGIT ER CALCULATION ER JONNO MAN 'BL' REGISTER E SAVE ASE JA PORE DL E MOV KORE PRINT KORA JABE
MOV DL,BL
;PRINT 
MOV AH,2
INT 21H


;exit to DOS
MOV AX,4C00H
INT 21H

MAIN ENDP
   END MAIN